import { createBar } from "../../shared/utils/barFactory";
import { DEFAULT_FONT_STACK } from "../../shared/constants/fonts";
import type { BarChartSettings } from "../../types/bar";

const defaultPaletteName = "vibrant";
const baseBars = Array.from({ length: 3 }, (_, index) =>
  createBar(index, defaultPaletteName)
);

export const defaultBarChartSettings: BarChartSettings = {
  data: baseBars,
  showErrorBars: false,
  showValueLabels: true,
  // Chart orientation
  orientation: "vertical",
  // Legacy settings (kept for backward compatibility)
  barOpacity: 0.85,
  barBorderWidth: 2,
  // Global bar design settings
  barCornerRadius: 16,
  barCornerStyle: "top",
  barGap: 0.15,
  // Global border settings
  showBorder: true,
  globalBorderWidth: 2,
  // Global bar styling defaults
  globalFillColor: "#3b82f6",
  globalFillOpacity: 0.85,
  globalBorderColor: "#0f172a",
  globalBorderOpacity: 1.0,
  globalPattern: "solid",
  globalPatternColor: "#ffffff",
  globalPatternOpacity: 0.35,
  globalPatternSize: 8,
  backgroundColor: "#0f172a",
  canvasPadding: 48,
  textColor: "#f8fafc",
  globalFontFamily: DEFAULT_FONT_STACK,
  titleColor: "#f8fafc",
  titleFontFamily: DEFAULT_FONT_STACK,
  titleIsBold: true,
  titleIsItalic: false,
  titleIsUnderline: false,
  titleOffsetX: 0,
  title: "Custom bar chart",
  titleFontSize: 20,
  titleOffsetY: 0,
  subtitle: "",
  subtitleFontSize: 16,
  subtitleOffsetY: 0,
  subtitleOffsetX: 0,
  subtitleColor: "#cbd5f5",
  subtitleFontFamily: DEFAULT_FONT_STACK,
  subtitleIsBold: false,
  subtitleIsItalic: false,
  subtitleIsUnderline: false,
  xAxisTitleFontSize: 14,
  yAxisTitleFontSize: 14,
  xAxisTickFontSize: 12,
  yAxisTickFontSize: 12,
  xAxisTickOffsetX: 0,
  xAxisTickOffsetY: 0,
  yAxisTickOffsetX: 0,
  yAxisTickOffsetY: 0,
  valueLabelFontSize: 12,
  valueLabelOffsetY: 0,
  valueLabelOffsetX: 0,
  xAxisTitleOffsetY: 0,
  yAxisTitleOffsetX: 0,
  yAxisMin: null,
  yAxisMax: null,
  aspectRatio: 0.6,
  customWidth: null,
  customHeight: null,
  errorBarMode: "global",
  errorBarColor: "#f8fafc",
  errorBarWidth: 2,
  errorBarCapWidth: 12,
  // Axis synchronization settings
  axesSynced: true,
  yAxisTickStep: null,
  exportScale: 2,
  exportTransparent: false,
  exportFileName: "barplot",
  paletteName: defaultPaletteName,
  // Plot box border settings
  showPlotBox: false,
  plotBoxLineWidth: 1.5,
  plotBoxColor: "#e2e8f0",
  xAxis: {
    showAxisLines: true,
    showTickLabels: true,
    showGridLines: false,
    axisLineColor: "#e2e8f0",
    axisLineWidth: 1.5,
    tickLabelColor: "#e2e8f0",
    tickLabelOrientation: 0,
    gridLineColor: "#475569",
    gridLineStyle: "solid" as const,
    gridLineOpacity: 0.6,
    gridLineWidth: 1,
    title: "Categories",
  },
  yAxis: {
    showAxisLines: true,
    showTickLabels: true,
    showGridLines: true,
    axisLineColor: "#e2e8f0",
    axisLineWidth: 1.5,
    tickLabelColor: "#e2e8f0",
    tickLabelOrientation: 0,
    gridLineColor: "#334155",
    gridLineStyle: "solid" as const,
    gridLineOpacity: 0.6,
    gridLineWidth: 1,
    title: "Values",
  },
};
