import { createBar } from "./shared/utils/barFactory";
import { DEFAULT_FONT_STACK } from "./shared/constants/fonts";
import type { ChartSettings } from "./types";

const defaultPaletteName = "vibrant";
const baseBars = Array.from({ length: 3 }, (_, index) =>
  createBar(index, defaultPaletteName)
);

export const defaultSettings: ChartSettings = {
  bars: baseBars,
  showErrorBars: false,
  showValueLabels: true,
  barOpacity: 0.85,
  barBorderWidth: 2,
  barCornerRadius: 16,
  barCornerStyle: "top",
  barGap: 0.15,
  backgroundColor: "#0f172a",
  canvasPadding: 48,
  textColor: "#f8fafc",
  globalFontFamily: DEFAULT_FONT_STACK,
  titleColor: "#f8fafc",
  titleFontFamily: DEFAULT_FONT_STACK,
  titleIsBold: true,
  titleIsItalic: false,
  titleIsUnderline: false,
  titleOffsetX: 0,
  title: "Custom bar chart",
  titleFontSize: 20,
  titleOffsetY: 0,
  subtitle: "",
  subtitleFontSize: 16,
  subtitleOffsetY: 0,
  subtitleOffsetX: 0,
  subtitleColor: "#cbd5f5",
  subtitleFontFamily: DEFAULT_FONT_STACK,
  subtitleIsBold: false,
  subtitleIsItalic: false,
  subtitleIsUnderline: false,
  axisTitleFontSize: 14,
  axisTickFontSize: 12,
  valueLabelFontSize: 12,
  valueLabelOffsetY: 0,
  valueLabelOffsetX: 0,
  xAxisTitleOffsetY: 0,
  yAxisTitleOffsetX: 0,
  yAxisMin: null,
  yAxisMax: null,
  aspectRatio: 0.6,
  customWidth: null,
  customHeight: null,
  errorBarMode: "global",
  errorBarColor: "#f8fafc",
  errorBarWidth: 2,
  errorBarCapWidth: 12,
  yAxisTickStep: null,
  exportScale: 2,
  exportTransparent: false,
  exportFileName: "barplot",
  paletteName: defaultPaletteName,
  xAxis: {
    showAxisLines: true,
    showTickLabels: true,
    showGridLines: false,
    axisLineColor: "#e2e8f0",
    axisLineWidth: 1.5,
    tickLabelColor: "#e2e8f0",
    tickLabelOrientation: 0,
    gridLineColor: "#475569",
    gridLineStyle: "solid" as const,
    gridLineOpacity: 0.6,
    gridLineWidth: 1,
    title: "Categories",
  },
  yAxis: {
    showAxisLines: true,
    showTickLabels: true,
    showGridLines: true,
    axisLineColor: "#e2e8f0",
    axisLineWidth: 1.5,
    tickLabelColor: "#e2e8f0",
    tickLabelOrientation: 0,
    gridLineColor: "#334155",
    gridLineStyle: "solid" as const,
    gridLineOpacity: 0.6,
    gridLineWidth: 1,
    title: "Values",
  },
};
